Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mproject.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace mproject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Album()
        {
            return View();
        }
        public IActionResult Upload()
        {
            return View();
        }
        public IActionResult Manage()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ImageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using mproject.Data;
using mproject.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using mproject.Utility;
namespace mproject.Controllers
{
    public class ImageController : Controller
    {

        private readonly AppDbContext context;
        public ImageController(AppDbContext Context)
        {
            this.context = Context;
        }
        [HttpPost]
        public async Task<IActionResult> Upload(List<IFormFile> files)
        {
            foreach (var file in files)
            {
                var imageName = Path.GetFileNameWithoutExtension(file.FileName);
                var extension = Path.GetExtension(file.FileName);
                var uploadedby = HttpContext.User.Identity.Name;
                var imageModel = new ImageonDBModel
                {
                    CreatedOn = DateTime.UtcNow,
                    FileType = file.ContentType,
                    Extension = extension,
                    ImageName = imageName,
                    UploadedBy = uploadedby,
                };
                using (var dataStream = new MemoryStream())
                {
                    await file.CopyToAsync(dataStream);
                    imageModel.Data = dataStream.ToArray();
                }
                context.ImageOnDatabase.Add(imageModel);
                context.SaveChanges();
            }
            return RedirectToAction("Upload", "Home");
        }
        public async Task<IActionResult> ShowImage(imageconvert img)
        {
            return View();
        }
    }
}

Views/Home/Album.cshtml
<!DOCTYPE html>
<html>
<body>
    <form>
    </form>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/Manage.cshtml
<h1>HELLO</h1>

Views/Home/Upload.cshtml
<!DOCTYPE html>
@model ImageonDBModel
<html>
<body>
    <p>Click on the "Choose File" button to upload a file:</p>

    <form method="post" enctype="multipart/form-data">
        <input type="file" name="file" accept="image/png" />
        <button class="btn btn-success" type="submit" asp-controller="Image" asp-action="Upload">Upload to Database</button>
    </form>
</body >
</html >